# Generated by Django 4.1.4 on 2022-12-07 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='miembro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombres', models.CharField(max_length=250, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=250, verbose_name='Apellidos')),
                ('nacionalidad', models.CharField(max_length=250, verbose_name='Nacionalidad')),
                ('numero_de_documento', models.CharField(max_length=250, verbose_name='CIN')),
                ('fecha_de_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono_particular', models.CharField(max_length=250, verbose_name='Tel. Part.')),
                ('telefono_corporativo', models.CharField(max_length=250, verbose_name='Tel. Corp.')),
                ('mail_particular', models.CharField(max_length=250, verbose_name='Mail Part.')),
                ('mail_corporativo', models.CharField(max_length=250, verbose_name='Mail Corp.')),
                ('fecha_de_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_de_salida', models.DateField(verbose_name='Fecha de Salida')),
                ('motivo_de_salida', models.CharField(max_length=250, verbose_name='Motivo de Salida')),
                ('cargo', models.CharField(max_length=250, verbose_name='Cargo')),
                ('notas_adicionales', models.CharField(max_length=250, verbose_name='Notas')),
                ('contribuyente_set', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20, verbose_name='SET')),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado')], max_length=25, verbose_name='Estado Civil')),
                ('hijos', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=25, verbose_name='Hijos')),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('PNM', 'Prefiero no mencionarlo')], max_length=25, verbose_name='Genero')),
                ('Asig_Organigrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.staffprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
