# Generated by Django 4.1.4 on 2022-12-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pymes', '0004_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('sigla', models.CharField(max_length=25, verbose_name='Sigla')),
                ('empleado_o_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymes.cliente')),
                ('nombre_de_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymes.departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
