# Generated by Django 3.2.14 on 2022-12-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('staff_no', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_name', models.TextField(max_length=200)),
                ('designation', models.CharField(max_length=10)),
                ('reporting_officer', models.IntegerField()),
            ],
        ),
    ]
